apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-webapp
  labels:
    app: static-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-webapp
  template:
    metadata:
      labels:
        app: static-webapp
    spec:
      containers:
      - name: static-webapp
        image: salmaan21/statiwebapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-webapp-service
spec:
  selector:
    app: static-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
